remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: North East Data Scientists 2022
description: Slides from the North East Data Scientist's 2022 meetup events
logo: /assets/neds-logo.jpeg
